import { defineStore } from 'pinia'

// useStore could be anything like useUser, useCart
// the first argument is a unique id of the store across your application
export const useCars = defineStore('cars', {
    //初期値
    state: () => ({
        cars: [
            {
                id:1,
                sell:true,
                name:'T社',
                companyType: '一般車',
                carType: 'コンパクトカー',
                carNum: 150000,
                record: true,
                product_length: 100,
                product_quality: '標準',
                price:50000,
                rieki:-300000,
            },
            {
                id:2,
                sell:true,
                name:'T社',
                companyType: '一般車',
                carType: 'SUV',
                carNum: 50000,
                record: true,
                product_length: 150,
                product_quality: '標準',
                price:50000,
                rieki:300000,
            },
            {
                id:3,
                sell:true,
                name:'B社',
                companyType: '高級車',
                carType: 'セダン',
                carNum: 100000,
                record: false,
                product_length: 100,
                product_quality: '標準',
                price:50000,
                rieki:300000,
            },
            {
                id:4,
                sell:true,
                name:'B社',
                companyType: '高級車',
                carType: 'SUV',
                carNum: 50000,
                record: true,
                product_length: 150,
                product_quality: '標準',
                price:50000,
                rieki:300000,
            },
            {
                id:5,
                sell:true,
                name:'N社',
                companyType: '一般車',
                carType: 'ミニバン',
                carNum: 200000,
                record: false,
                product_length: 150,
                product_quality: '標準',
                price:50000,
                rieki:300000,
            },
            {
                id:6,
                sell:true,
                name:'N社',
                companyType: '一般車',
                carType: 'コンパクトカー',
                carNum: 300000,
                record: false,
                product_length: 100,
                product_quality: '標準',
                price:50000,
                rieki:300000,
            },
            {
                id:7,
                sell:true,
                name:'V社',
                companyType: '高級車',
                carType: 'セダン',
                carNum: 50000,
                record: true,
                product_length: 100,
                product_quality: '標準',
                price:50000,
                rieki:300000,
            },
            {
                id:8,
                sell:true,
                name:'V社',
                companyType: '高級車',
                carType: 'SUV',
                carNum: 70000,
                record: true,
                product_length: 150,
                product_quality: '標準',
                price:50000,
                rieki:300000,
            },
        ],
    }),
})